server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework.web: DEBUG